micronaut:
    application:
        name: movies-web-service
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
            swagger-ui:
                paths: classpath:META-INF/swagger/views/swagger-ui
                mapping: /swagger-ui/**
            design:
                paths: "classpath:design"
                mapping: /design/**
    security:
        endpoints:
            login:
                enabled: false
        authentication: bearer
        token:
            jwt:
                signatures:
                    secret:
                        generator:
                            secret: ${JWT_GENERATOR_SIGNATURE_SECRET:Epvncq4kEXXDVZg4lxD1D58cN09FxlMc}

    mail:
        enabled: true
        default-configuration: default
        configurations:
            default:
                transport:
                    protocol: smtp
                    host: localhost
                    port: 1025
                auth:
                    username: ""
                    password: ""

redis:
    uri: redis://localhost

tmdb-client:
    api:
        url: https://api.themoviedb.org/3

tmdb:
    token: ${TMBD_TOKEN:`Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiMjZhZGMxNGQyZmUzYWM5NGFkYzJiZGZmOWFhOTQ5ZSIsInN1YiI6IjY1YTNjNzY2MWYwMjc1MDEyZTA4YWQyMyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.2Ov2n9yawFR-BA-fSY917zFyrJIL0oD37zWq-oBb_YI`}

jpa:
    default:
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true

datasources:
    default:
        url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/lulugyda`}
        username: ${JDBC_USER:lulugyda}
        password: ${JDBC_PASSWORD:password}
        driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}

flyway:
    enabled: true
    datasources:
        default:
            enabled: true
            baseline-on-migrate: true


ftp:
    host: ${FTP_HOST:localhost}
    port: ${FTP_PORT:21}
    username: ${FTP_USER:myuser}
    password: ${FTP_PASS:mypass}

twilio:
    account-sid: ${TWILIO_ACCOUNT_SID:AC05efa933bf9e9e65adc48b64d8ce6851}
    auth-token: ${TWILIO_AUTH_TOKEN:7580a052174c311c2ac98f9e35df29ed}

logger:
    levels:
        io.micronaut.security: DEBUG


