micronaut:
    application:
        name: movies-web-service
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
            swagger-ui:
                paths: classpath:META-INF/swagger/views/swagger-ui
                mapping: /swagger-ui/**
            design:
                paths: "classpath:design"
                mapping: /design/**
    security:
        authentication: bearer
        token:
            jwt:
                signatures:
                    secret:
                        generator:
                            secret: ${JWT_GENERATOR_SIGNATURE_SECRET:Epvncq4kEXXDVZg4lxD1D58cN09FxlMc}

    mail:
        enabled: true
        default-configuration: default
        configurations:
            default:
                transport:
                    protocol: smtp
                    host: localhost
                    port: 1025
                auth:
                    username: ""
                    password: ""

redis:
    uri: redis://localhost

tmdb-client:
    api:
        url: https://api.themoviedb.org/3

tmdb:
    token: ${TMBD_TOKEN:`Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxNjgwZGZjZDcyNWZhNTg0NGE0NDdlMTA5Y2VlZjBhOSIsInN1YiI6IjY1YTNhZDUwMzliNmMzMDBjMTc3YjhiZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.E2gRJmvcOm8MacFQClD_Gu_FhyDX06kBNNjZr4_v6I4`}

jpa:
    default:
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true

datasources:
    default:
        url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/lulugyda`}
        username: ${JDBC_USER:lulugyda}
        password: ${JDBC_PASSWORD:password}
        driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}

flyway:
    enabled: true
    datasources:
        default:
            enabled: true
            baseline-on-migrate: true
